# Generated by Django 3.2.3 on 2021-05-31 03:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0004_auto_20210530_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[0], size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[0], size=None),
        ),
    ]
