# Generated by Django 3.2.3 on 2021-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, unique=True)),
                ('displayName', models.CharField(max_length=64, null=True)),
                ('tagLine', models.CharField(max_length=128, null=True)),
                ('following', models.ManyToManyField(related_name='_users_api_user_following_+', to='users_api.User')),
            ],
        ),
    ]
