# Generated by Django 3.2.3 on 2021-05-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_api', '0002_rename_comment_text_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
