# Generated by Django 3.2.3 on 2021-05-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_api', '0003_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=256),
        ),
    ]
