# Generated by Django 3.2.3 on 2021-05-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_api', '0004_auto_20210530_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
