# Generated by Django 3.2.3 on 2021-05-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_api', '0005_rename_post_id_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
